package rules;

import com.app.*;

rule "Distance category SHORT"
    agenda-group "level1"
    when
        $f: Flight(flightDistanceKm <= 1500, distanceCategory == null)
    then
        modify($f) { setDistanceCategory(DistanceCategory.SHORT) };
end

rule "Distance category MEDIUM - within EU"
    agenda-group "level1"
    when
        $f: Flight(flightDistanceKm > 1500, isWithinEu == true, distanceCategory == null)
    then
        modify($f) { setDistanceCategory(DistanceCategory.MEDIUM) };
end

rule "Distance category MEDIUM - outside EU 1500-3500"
    agenda-group "level1"
    when
        $f: Flight(flightDistanceKm > 1500, flightDistanceKm <= 3500, isWithinEu == false, distanceCategory == null)
    then
        modify($f) { setDistanceCategory(DistanceCategory.MEDIUM) };
end

rule "Distance category LONG - outside EU over 3500"
    agenda-group "level1"
    when
        $f: Flight(flightDistanceKm > 3500, isWithinEu == false, distanceCategory == null)
    then
        modify($f) { setDistanceCategory(DistanceCategory.LONG) };
end
