package rules;

import com.app.*;

query compensation250(String $fid)
    Flight(flightId == $fid, isRegulationApplicable == true, distanceCategory == DistanceCategory.SHORT)
    Incident(flightId == $fid, isExtraordinary == false,
        ( (type == IncidentType.DELAY && delayAtDestinationHours >= 3)
          || type == IncidentType.CANCELLATION
          || type == IncidentType.DENIED_BOARDING ) )
end

query compensation400(String $fid)
    Flight(flightId == $fid, isRegulationApplicable == true, distanceCategory == DistanceCategory.MEDIUM)
    Incident(flightId == $fid, isExtraordinary == false,
        ( (type == IncidentType.DELAY && delayAtDestinationHours >= 3)
          || type == IncidentType.CANCELLATION
          || type == IncidentType.DENIED_BOARDING ) )
end

query compensation600(String $fid)
    Flight(flightId == $fid, isRegulationApplicable == true, distanceCategory == DistanceCategory.LONG)
    Incident(flightId == $fid, isExtraordinary == false,
        ( (type == IncidentType.DELAY && delayAtDestinationHours >= 4)
          || type == IncidentType.CANCELLATION
          || type == IncidentType.DENIED_BOARDING ) )
end

query hotelRight(String $fid)
    Flight(flightId == $fid, isRegulationApplicable == true)
    Incident(flightId == $fid, isRequiresOvernightStay == true)
end

query ticketRefund(String $fid)
    Flight(flightId == $fid, isRegulationApplicable == true)
    Incident(flightId == $fid,
        ( (type == IncidentType.DELAY && delayHours >= 5)
          || type == IncidentType.CANCELLATION
          || type == IncidentType.DENIED_BOARDING ) )
    Passenger(flightId == $fid, choice == PassengerChoice.REFUND)
end

query alternativeFlight(String $fid)
    Flight(flightId == $fid, isRegulationApplicable == true)
    Incident(flightId == $fid,
        ( (type == IncidentType.DELAY && delayHours >= 5)
          || type == IncidentType.CANCELLATION
          || type == IncidentType.DENIED_BOARDING ) )
end

query downgradeRefund(String $fid)
    Incident(flightId == $fid, isDowngraded == true)
end

query refuseVoucherClaimCash(String $fid)
    Right(type == RightType.COMPENSATION)
end
